travis:
  secure:
    BINSTAR_TOKEN: tCss9FBalUISjQivj/A8krU0YX5cugyRfFqTnmXNrlgCzL/+I1rL6trtFlJsF0ZOt64OwdfTyeaaFWtgVu+HdkRCDfdOu47fClNoYOSri8BV7/R56coCYzNkbVvvBWjBj6sWDq8PBmhTGxFr521kH0RKZbdXEaZjdRlncPWEPmpcgmWvCcgUiIqVhvLmh3GkBU75uOa7NxX+/vkWGheWatqqo28fLM41CNFqp1xiyhDtjvTJ/O90iVnvwobp5Nff0jqJDnp+EUflGnMj+MbNAkf0h8x6CWaYz+sw49ygit7pylRKO+FwBgLkFSKzrA/LOxES346eXe2v50FODHMriwi5kRtKIeS+5s9OkgV4vZnq8HddydStjbZnEuTk/xcGgBZagPejDkxcpH5xfp+g6heHq9I48RHZyCuEAvnz5vujGwWlSiCZSczXn9rNUuoF31qOOTsNz+vaCnvn0jPZ4DjxjEVogkuVp9CiH4NOkEkQYAfO8QLTRiTQ6kGFe+LH+MXmjIX6pg7McB4YGr+3Q1VJzx3ELJFba8NbiAbO5Q0R82CkxgLeZpt0DLIGHOpjVh6Qo6kcZUu4qLuoM9xuTjMDCTiLXTs9qZDcnqXlmfCyl4MLykd0gtOtmtrlexmVUuHV23dFZMSd50TczLS9+FrtgPZgPkG9RL5p9CtbJoQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
