travis:
  secure:
    BINSTAR_TOKEN: lrcKCavBFGD8HeuGlIs9i/7GSB3FDMJsZthD7JMUzIAcvGvnL/Uo4ggmJM/uaMCwXxWFr30uiD4jXG0j5WQuWgnIdZAgWUyO8c6TF/NyWkQgEUNaVXvsDbojX0gXrtPKHxasYtPzXOFD628+p5JFBUpUlGqbR3hzxuO4WYU8H5gG5pTcLTZ2vT9W0DzaTIcRUdSFB5SQD/K50hUPnRrQjrXAXt7JZJIPhZgInL59TNC5i7dqdSUOzoA24k2xYDN2ZpkMy0X5Q3m/dGkAfwDJYVi2Gq/DV3ZPYeSlxMDqyI6vDetYJa7VFOlIH33O/BQjWggFLZjQxTW6/Zf6sTh1DpcZ70R0CMZDShIyjRiYgV08WEjalxKHtV1ZQ7Y++1WrmETSnAadQ2yt7ARqYyD9VCmIPRFayI/0DzTkJbABdtNboZ6fvO7XQt8X6rY86HkOue4DhMTBJ4m6xnsTXT5hb5hmT0PiEybsYYjk0S7M06E2d9MRpMKRt8bd19iTqjZP0qK3M3av/Kf0JDIO8t0TxyO2HBMnW1dqYDsWcwr7RO7q++c8y+cSA1posJq7IfrkLLYLNM0Bxdo4kSrCfs+G4rA33isCx3F0oHwML3rRXY3+AGekFQz2b3R4kwmVBhjVTJi8r6vg1DzksLRONy1szmls+tCwC2Sxt3ccToD04o4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
