travis:
  secure:
    BINSTAR_TOKEN: 1pqqUA4pxc5LkdZ92s8ZGErgQkwmg42oGavLc08ze3LLnC1KvBXGXqUhhJJOr5eFIFghpLJJMpdN8Zsh4W0ArqLT2AV+O8/2LqKRMeiFG1R8nC8kew2SWGkE0lvn5+04/3R4XcGmjESP1NMy3gDPAd70Xa6dodBaxbAKpOVTuHJhUk2pIwLW3dsUKNqIofWUcsNUZ30eaows+ieJWqc1132TdiwqlnB2aoc2nBVIWQ1KSxFQ90Pt6y2x/MRVAEef03nKUDb6arMBuI84iKcm2Ou0Brnn5SP1puxyRnV9pwTZ3R9LB7tFSCaB9urm86jXWgxegwjklnZtIw9idb195eproOiXcyKwFvg3LgUH+98Ma3YCEIG5o7nsuFgfi3GcW7S5JnuKnyZgJBcR63V4czNYjtopGnrYNfmsb/93RvKOVEkPWCV9JNeknsN2Bm5rlF3ueCyXkTtaYmmDu5mWneOVHV3VisorP57s6hlvhHG2ZlRUiZAsWWYO/NaMaN4JUWB2M08Lp0qc+KSORgx6Mah3bMO3RXUKj3cGJoeNLY8unpb3PxrJ6zzRtmfGAoQSkuqLm5ZXV8MS9EzSdubv0bL5KkT/zSJDUjHFFeUPan/dgtXzQYJL3wgCrVHrNBc5Jgm9Ust42zARLR5tDfJTxQsct0hKf2MQtax/yfAIVgY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
